### ISSUE TITLE
Gateway - make Earn page compatible with phones

### ISSUE THREAD

**Issue by CAPtheorem** [omgnetwork/optimism-v2#106]
See screenshot of non-ideal layout

<img width="508" alt="Screen Shot 2021-10-28 at 12 01 54 PM" src="https://user-images.githubusercontent.com/79423264/139319136-431ac04d-1d45-4e05-a18d-c970bdd4b876.png">

**Comment by sk-enya** [comment]
Fixes as been done and looks like screen attached below.
<img width="437" alt="Screenshot 2021-11-01 at 1 13 23 AM" src="https://user-images.githubusercontent.com/86316370/139599071-c07b519b-a9f6-4a45-8376-c391ed63063d.png">

**Comment by sk-enya** [comment]
Closing the issue as it has been already merged
