### ISSUE TITLE
Gateway - add $UST to bridge

### ISSUE THREAD

**Issue by zukoboba** [omgnetwork/optimism-v2#114]
I propose we add [$UST](https://www.coingecko.com/en/coins/terra-usd), Terra's native stable coin . It's been supported across multiple chains such as Solana and Harmony, as well as many decentralized exchanges such as Sushiswap and Omsosis. The token contract is ` 0xa47c8bf37f92abed4a126bda807a7b7498661acd`.

We've chatted some with the Terraform labs team on the details of a potential partnership. We made a post a few months ago on their forum [outlining possible areas](https://agora.terra.money/t/bringing-ust-to-boba-ethereum-l2/1961). We don't have anything set in stone (yet), but I think it'd build some goodwill to be proactive about supporting $UST early on for the Boba gateway.

**Comment by CAPtheorem** [comment]
Great idea - on it

**Comment by zukoboba** [comment]
thanks!

**Comment by souradeep-das** [comment]
Is there a preferred Rinkeby version of UST that we know of?

**Comment by zukoboba** [comment]
What do you mean? Not sure how $UST differs on rinkeby

**Comment by souradeep-das** [comment]
The rinkeby $UST token address i mean. (if there's a preferred/existing one) for the 'rinkeby gateway'
If there's none, no worries.

**Comment by CAPtheorem** [comment]
Merged - support for wrapped $UST will be live shortly: https://github.com/omgnetwork/optimism-v2/pull/118
