### ISSUE TITLE
Blockexplorer only shows new activity since re-genesis

### ISSUE THREAD

**Issue by jwboba** [omgnetwork/optimism-v2#116]
https://blockexplorer.boba.network/tokens is not taking into account the holders pre-regenesis (there were more than 1000 wallets) and also not showing some tokens like Sushi (there's currently a LP balance on it)

Individual wallets also not showing the token balance for those that bridged pre-regenesis, other than ETH:
![image](https://user-images.githubusercontent.com/90710496/139517798-90cf0bf5-9225-4cf3-b23e-c85afe94cbf3.png)

Gateway shows the proper balance though.

**Comment by CAPtheorem** [comment]
Hello @jwboba - thanks for your report. The blockexplorer only shows new activity post-regenesis (Oct. 28), so it's working as intended/designed. Notably, the blockexplorer is not the right place to go for accurate stats on Boba TVL or accounts.
