### ISSUE TITLE
Error on classic L1 bridge (Ledger / Blind signing initially off, then error after enabling blind signing)

### ISSUE THREAD

**Issue by Claude-Mon** [omgnetwork/optimism-v2#119]
Can not proceed on classic bridge L1. After approval, apparently my ledger s did not have blind signing enabled. After correcting this and checking every available update, the following error shows up after hitting the bridge knob. (See screenshots)
![97691D5B-1AD0-44CA-94F9-713DF994DAD9](https://user-images.githubusercontent.com/93547358/139723924-0d632ba0-8838-4075-9be1-87d6e1f6666d.jpeg)
![F91ED437-9BD4-4673-8E86-A2365B6D33B2](https://user-images.githubusercontent.com/93547358/139723934-2273f040-2611-41a0-9fa2-926be73ba139.jpeg)

**Comment by CAPtheorem** [comment]
@Claude-Mon thanks for your report. GitHub issues (this site) are monitored 24/7 by engineering so this is fastest way to get help. The error message means that one or more contract addresses are not defined, and therefore, null.ToLower() fails, so this is either a problem with the AddressManager, or something quite esoteric. To figure this out, we need the early logs. To generate them:

1. Refesh your browser window.
2. Turn on developer logging, just like you have done. 
3. Take a screenshot of what you see right after you clicked "Connect using browser wallet" on the splash screen, blanking out your wallet address first (your wallet address will be on the third line of the debug output). It should look like this:

<img width="745" alt="Screen Shot 2021-11-01 at 11 52 48 AM" src="https://user-images.githubusercontent.com/79423264/139725323-896ca9fc-c8ca-4f86-a6fd-595fa80a760f.png">

Specifically, any error messages within the gateway initialization would be directly relevant to your problem.

**Comment by Claude-Mon** [comment]
Thanks, 
![Uploading 31D03CFA-F31A-464A-93AD-8960547C7E30.jpeg…]()
I hope this is what you need

**Comment by Claude-Mon** [comment]
![43B0F723-363B-4005-84E8-0E4781FF53BD](https://user-images.githubusercontent.com/93547358/139728142-56d97673-48ad-434b-a66b-b9bdd2ab760c.jpeg)
![949DA3DC-1D67-40D9-A940-0832763D57F2](https://user-images.githubusercontent.com/93547358/139728151-2677a471-d52b-402c-b7b2-a014b8174bd7.jpeg)

**Comment by Claude-Mon** [comment]
![Uploading DAE7EB13-F803-4498-9EDC-6A0EB49B5E44.jpeg…]()

**Comment by CAPtheorem** [comment]
Ok, thats looks precisely how it should look like. (I'll delete those screen grabs BTW)

**Comment by Claude-Mon** [comment]
The first eth transaction for approval did proceed without any issue (appr$21)

**Comment by CAPtheorem** [comment]
Ok thanks! We'll have to recreate your specific workflow here - Ledger with blind signing off, then try TX, then fail due to blind signing off, then turn on blind signing, then retry TX, then OMG bridge fail with address undefined error message.

**Comment by Claude-Mon** [comment]
exactly

**Comment by CAPtheorem** [comment]
Found the problem, fix pushed, deployment to production pending. We will deploy the fix at the same time as we add support for wrapped Terra ($UST). ETA about 1 hour.

**Comment by Claude-Mon** [comment]
Okay, thanks. I’ll wait. Can you confirm later on the fix? Then I’ll try again

**Comment by CAPtheorem** [comment]
Yes will confirm once live
