### ISSUE TITLE
Fraud Detector's URI returns 502

### ISSUE THREAD

**Issue by gamedazed** [omgnetwork/optimism-v2#134]
`wget -vvv https://replica.boba.network:8081/state-dump.latest.json`
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving replica.boba.network (replica.boba.network)... 52.71.166.105, 52.206.20.254, 52.86.91.181, ...
Connecting to replica.boba.network (replica.boba.network)|52.71.166.105|:8081... connected.
HTTP request sent, awaiting response... 502 Bad Gateway
2021-11-05 08:46:42 ERROR 502: Bad Gateway.

**Comment by CAPtheorem** [comment]
Thank you for your report! The community fraud detector has been re-written in python and has just been released: 

[Community Fraud Detector](https://github.com/omgnetwork/optimism-v2/tree/develop/boba_community/fraud-detector)

Also, the user documentation has been added to docs.boba.network:

[Community Fraud Detector User Documentation](https://docs.boba.network/user-docs)

Please allow for up to one hour for the various caches to update, before those links will show all the right material.
