### ISSUE TITLE
Typo 

### ISSUE THREAD

**Issue by Elves420** [omgnetwork/optimism-v2#153]
![19B22E40-72C0-4EA5-9510-033D87EA21F7](https://user-images.githubusercontent.com/94238350/141652252-d080afac-287e-46ae-b766-92093f59d415.jpeg)

Typo on the gateway, 

DAO section, click create proposal. Last word on the sentence. “Bridghe”

**Comment by CAPtheorem** [comment]
Thank you! Will be corrected today.
