### ISSUE TITLE
Gateway - add $UMA to bridge 

### ISSUE THREAD

**Issue by zukoboba** [omgnetwork/optimism-v2#163]
I propose we add $UMA, UMA's native protocol token. We have _a lot_  of cool things we're doing with them in store, and would be great to show their community some love before we announce. The token contract is 0x04fa0d235c4abf4bcf4787af4cf447de572ef828.

https://www.coingecko.com/en/coins/uma

**Comment by Boyuan-Chen** [comment]
#256
