### ISSUE TITLE
Layer1 -> Layer2 Bridge Failing

### ISSUE THREAD

**Issue by GenericProgramer** [omgnetwork/optimism-v2#166]
System Configuration: Nano Leder, Metamask
Browsers: Chrome and Brave
Blind Signing Enabled

Other Information:
The wallet was a legacy one created in 2017 on a nano ledger. When I choose it in metamask it says legacy mew, and doesn't show up in the Ledger Live section.

Issue:
I tried to bridge between L1-L2 before the snapshot the transaction just sat waiting for confirmation. There were no errors in the dev console to suggest there was anything wrong. I tried with several browsers and updated the nano ledger etc. I came back to it this morning and the transaction showed as cancelled.

I tried again this morning with no luck. Interestingly I only had one interaction with metamask and nothing popped up on the nano ledger to confirm.

Other steps:
After the snapshot, I created a new wallet on the nano ledger transferred the tokens to that wallet and then managed to successfully bridge (3) interactions with metamask.

I fear this won't allow me to get the Boba airdrop.

**Comment by CAPtheorem** [comment]
It's hard to debug this remotely, but it sounds like the issue was that the 2017 Ledger/wallet was not talking to MetaMask correctly (and also not appearing in Ledger Live). Somewhat unrelatedly, Chrome and Firefox tend to more reliable than Brave in terms of MetaMask/Ledger workflow.

**Comment by GenericProgramer** [comment]
This was closed with no discussion or steps to help debug this issue. As noted in the request, I did try this on several browsers including chrome and firefox. I can see an interact with the wallet in Ledger live.
