### ISSUE TITLE
Run Boba API Node - Genesis Data

### ISSUE THREAD

**Issue by ceds** [omgnetwork/optimism-v2#191]
I'm trying to run a Boba API node.  I built GETH located here:

https://github.com/omgnetwork/optimism-v2/tree/develop/l2geth

And starting it as such:

./build/bin/geth --syncmode "fast" --maxpeers 100  --rpc --rpcapi="net,web3,eth,txpool" --rpcaddr="0.0.0.0"  --ws --wsapi="net,web3,eth,txpool" --wsaddr="0.0.0.0" --rollup.verifier

However, the genesis data seems to be missing.  Where can I locate the genesis file for the Boba network so that I can do first init with it ?

**Comment by CAPtheorem** [comment]
Please follow these instructions, to get started:

[Boba Node](https://docs.boba.network/developer-docs/011_running-replica-node)

The state dump file you are looking for can be found [here](https://github.com/omgnetwork/optimism-v2/blob/develop/boba_community/boba-node/docker/state-dump.latest.json)

**Comment by ceds** [comment]
> Please follow these instructions, to get started:
> 
> [Boba Node](https://docs.boba.network/developer-docs/011_running-replica-node)
> 
> The state dump file you are looking for can be found [here](https://github.com/omgnetwork/optimism-v2/blob/develop/boba_community/boba-node/docker/state-dump.latest.json)

Thanks a lot!  Boba is indeed something I'm not used to.  Looks like a self-hosted GETH node is not actually following the network like it would with ETH GETH ?

**Comment by CAPtheorem** [comment]
> > Please follow these instructions, to get started:
> > [Boba Node](https://docs.boba.network/developer-docs/011_running-replica-node)
> > The state dump file you are looking for can be found [here](https://github.com/omgnetwork/optimism-v2/blob/develop/boba_community/boba-node/docker/state-dump.latest.json)
> 
> Thanks a lot! Boba is indeed something I'm not used to. Looks like a self-hosted GETH node is not actually following the network like it would with ETH GETH ?

It will follow along just like you are used to - once your (replica) geth has caught up with the boba geth, then you will see your replica follow along transaction by transaction (aka block by block - each TX on the L2 is its own block). If you are setting up things from scratch, make sure that you have your geth configured to run in replica mode:
```
      ROLLUP_BACKEND: 'l2'
      ROLLUP_VERIFIER_ENABLE: 'true' 
```

**Comment by CAPtheorem** [comment]
Following up @ceds - are you all set? Nodes running?
