### ISSUE TITLE
Failed to decode input data.

### ISSUE THREAD

**Issue by seniorboobies** [omgnetwork/optimism-v2#240]
Got this when I Bridged from L2 to L1. Waiting on my OMG to come to L1. Says the transaction is sent.  Confirmed by 42 block when I see it on the bob network but on the dash, it says this, STEP 0, NO SR HASH YET, PENDING. It's long after the completion.

**Comment by CAPtheorem** [comment]
This is for a L2->L1 fast bridge? You can check on the status in the "system analytics" tab on the gateway. I'm showing zero pending exits right now (Dec. 19 8:05 PM PST). Let me know if it did not go through by now and we can dig more.

**Comment by seniorboobies** [comment]
It came through.  Just freaked me out bec it took a lot longer than I thought.  Usually its done by the time it says.  Thanks.

**Comment by CAPtheorem** [comment]
Ok great! We are always here to help.
