### ISSUE TITLE
"Failed to decode input data"

### ISSUE THREAD

**Issue by jem778** [omgnetwork/optimism-v2#246]
Hello,

Would appreciate your assistance, pls. 

Initiated a Fast Bridge transfer of OMG from L2 to L1 over 12 hours ago:
BLOCK 254005 
L2 Hash: 0xa0f6278a201603c53e0f919a24c9c3f7acd297c52d661bb2942f75a5eeaf78df

I have yet to receive the OMG tokens on L1. It seems the OMG totals are still in L2 although in Transaction Details it shows Success & Confirmed. But  in Transaction Details > Input field  it shows "Failed to decode input data".

Can you please advise if the transaction had failed and what I should do next. I have already spent the Fast Bridge ETH Fee to initiate the transfer. Will wait your advice.

Thank you

**Comment by Boyuan-Chen** [comment]
Hi jem778,

Your tx was successfully replayed on L1. The L1 tx hash is [etherscan link](https://etherscan.io/tx/0x200edab0d2cd28eaad60e8460d6e0f8044890f556cacc16e5a15350b8a45e8a7). However, you exited 0 OMG, so you couldn't get OMG on L1. The `decode input data` is the blockscout's bug. The blockscout can't decode the data of the proxy contract.

**Comment by jem778** [comment]
Hi and thanks for your feedback. Despondently for me, I am not sure what this means "you exited 0 OMG'. Would I have inadvertently clicked something I shouldn't have?

**Comment by Boyuan-Chen** [comment]
The `For` section is 0 OMG, which means you exited 0 OMG. The front-end doesn't allow to exit 0 OMG. Could you please describe the steps that you used to exit the OMG?
<img width="485" alt="image" src="https://user-images.githubusercontent.com/46272347/147167883-06f4bcc1-2c15-4d0e-a3b8-c773f0ddaf70.png">

**Comment by jem778** [comment]
Looking back, I think I may not have had my Ledger device fully signed in at the moment of the transaction - see Metamask activity attached;
![image](https://user-images.githubusercontent.com/96530167/147168648-1311401a-4bba-4624-8c9e-e097713225df.png)
If this was the cause, then my mistake for sure. Will try again but more carefully this time.
