### ISSUE TITLE
Unable to receive BOBA tokens

### ISSUE THREAD

**Issue by rayphares** [omgnetwork/optimism-v2#254]
Hello, I have bridged my OMG tokens over to the BOBA network, however, I have not received any BOBA tokens into my wallet from the airdrop. What do I do to fix this issue?

**Comment by jliphard** [comment]
What is the displayed L1 and L2 status on the gateway/airdrop tab?

**Comment by rayphares** [comment]
Where will I see the status that is displayed?

**Comment by jliphard** [comment]
The status is displayed in the gateway - select the “airdrop” tab.

**Comment by zibi791** [comment]
Hi, I send OMG & ETH on Metamask so that tokens are visible on BOBA L1 network but during fast bridge from L1 to L2 there is no interactions on Metamask (no pop-up open for confirmation).
There is ETH Mainet and BOBA L2 at networks setings at Metamask.
So I'm unable recaive BOBA tokens.

**Comment by rayphares** [comment]
When I click on the airdrop tab, there are 2 different boxes that are displayed..

The L1 Airdrop box says this: There is no record of OMG in this specific non-custodial address (0xdEc1...3d90) on Ethereum during the snapshot.

If you had OMG on Ethereum during the snapshot, but are getting this message, please double check to make sure that you are accessing the gateway with the correct account/address.

Be advised that this claim tab has nothing to do with the exchanges. If you held OMG at an exchange during the L1 snapshot, the exchange, if it supported the airdrop, will drop your BOBA to you.

The L2 airdrop box says this: There is no record of OMG in this specific non-custodial address (0xdEc1...3d90) on Boba during the snapshot.

If you had OMG on Boba during the snapshot, but are getting this message, please double check to make sure that you are accessing the gateway with the correct account/address.

Be advised that this claim tab has nothing to do with the exchanges. If you held OMG at an exchange during the L1 snapshot, the exchange, if it supported the airdrop, will drop your BOBA to you.

**Comment by rayphares** [comment]
Does that mean that I am not eligible for the airdrop?

**Comment by rayphares** [comment]
I was storing my OMG tokens on my Celsius Wallet, not my MetaMask wallet, whenever the snapshot was taken, so I am unsure as to whether or not this could be the reason that I have not received the BOBA tokens through the airdrop or not. I have no clue what else to do in order to retrieve the tokens, IF I am even eligible. 

I really appreciate any and all help! :)

**Comment by bobachad** [comment]
@rayphares Celsius didn't partake in the airdrop so you're not eligible

**Comment by rayphares** [comment]
@bobachad, that is what I wasn't sure about...I appreciate your help SO much! Thank you!
