### ISSUE TITLE
Re-enable Turing result cache

### ISSUE THREAD

**Issue by mmontour1306** [omgnetwork/optimism-v2#308]
Re-enable the Turing result cache inside l2geth so that a transaction can call eth_estimateGas and generate only a single off-chain request, with the cached response being used for subsequent iterations of the gas-estimating loop as well as for an actual submission of that same transaction (within a few seconds). Generate some sort of key based on the transaction inputs and/or the user's (account,nonce) so that a new transaction will generate a fresh off-chain call rather than using old cached data.

**Comment by CAPtheorem** [comment]
active pr / feature in progress
