### ISSUE TITLE
L2 to L1 transfer failure

### ISSUE THREAD

**Issue by JettaRed** [omgnetwork/optimism-v2#312]
Got as far as STEP 1 and then an error message.  Blockchain explorer shows Success, but Input block shows "Failed to decode input data."

Transaction Hash: 0x97d22ea34e363003248b3276557224f7348e92c436ac9049be6dabccf42d3a91

https://blockexplorer.boba.network/tx/0x97d22ea34e363003248b3276557224f7348e92c436ac9049be6dabccf42d3a91/token-transfers

**Comment by JettaRed** [comment]
![image to attatch](https://user-images.githubusercontent.com/36326584/150607039-53fc9add-cd56-41cd-adfe-378c1eb412f1.jpeg)

**Comment by CAPtheorem** [comment]
That error (`missing response`) is a generic connectivity error that can happen due to poor WiFi etc - not a system problem. But will look into your transaction (which is a separate issue)

**Comment by JettaRed** [comment]
The transfer to https://blockexplorer.boba.network/address/**0x3a92ca39476ff84dc579c868d4d7de125513b034** shows multiple transactions from other addresses before and after my transaction with the same **Failed to decode** error.

Is that address a contract or bridging intermediate step?

**Comment by CAPtheorem** [comment]
1/ As shown in Etherscan, your bridging operation was successful and you have the OMG you exited in your wallet.
2/ The Error `missing response` indicates poor internet connectivity. 
3/ The blockexplorer message - `failed to decode` has nothing to do with your transaction (which succeeded).
4/ Yes, an L2->L1 bridging operation involves interactions with 6 separate contracts across the two chains

**Comment by JettaRed** [comment]
This is my transaction: https://blockexplorer.boba.network/tx/0x97d22ea34e363003248b3276557224f7348e92c436ac9049be6dabccf42d3a91/token-transfers

And this is my transaction in an attempt to bridge from L2 to L1:  https://blockexplorer.boba.network/address/0xC39248e20543bD7bb9f3c0498F43eBF069065Beb/transactions

The OMG went to address 0x3A92cA39476fF84Dc579C868D4D7dE125513B034 (identified as Lib_ResolvedDelegateProxy), but never was returned to my address 0xC39248e20543bD7bb9f3c0498F43eBF069065Beb
