### ISSUE TITLE
L2 to L1 transfer failure - missing OMG

### ISSUE THREAD

**Issue by JettaRed** [omgnetwork/optimism-v2#313]
To continue/reopen previous issue (https://github.com/omgnetwork/optimism-v2/issues/312), the OMG never returned to the ETH wallet on L1 after initiating a Fast Bridge from L2.  The ETH address is 0xC39248e20543bD7bb9f3c0498F43eBF069065Beb.  Is it still pending?

**Comment by CAPtheorem** [comment]
Yes, it is still pending as of now. You can see pending fast exits in the gateway - click `system analytics` and then click `Fast Exits`.

**Comment by JettaRed** [comment]
Thanks so much!

**Comment by CAPtheorem** [comment]
thanks for your patience @JettaRed - getting the L2->L1 bridging experience smooth is very much on our radar, and every slow bridging operation is one too many. We're on it.

**Comment by JettaRed** [comment]
I help people claim their BOBA tokens and have noticed that the L2>L1 bridging is taking longer and longer.  I suspect that as more people become aware of the airdrop and that they can still take advantage of it, things will slow down even more.

Thanks for your patience in explaining what is going on.  It can be unsettling to see (or not see) your OMG go on the bridge but not come off when you expect it to.

**Comment by JettaRed** [comment]
Finally came through!  Woohoo!

Thanks again!
