### ISSUE TITLE
Please confirm rebalancing date/time for LINK Layer 1

### ISSUE THREAD

**Issue by ranga247** [omgnetwork/optimism-v2#344]
Please confirm rebalancing date/time for LINK Layer 1.

Still not available to unstake.

**Comment by ranga247** [comment]
![Link Layer 1 - Available Balance Zero](https://user-images.githubusercontent.com/98461367/152231220-48510ba9-970c-43ff-9374-e7870f81583d.JPG)

See attached ZERO balance in  layer 1 LINK avaiable balance - hence I cannot unstake  my LINK

**Comment by CAPtheorem** [comment]
As noted in TG and in other PRs, the rebalancing will be completed on Feb 2, 10 PM US time.
