### ISSUE TITLE
Gateway - Pending Classic Deposit Bridge Message Still Showing

### ISSUE THREAD

**Issue by MitchellUnknown** [omgnetwork/optimism-v2#363]
On the 31th of january I deposited my Boba tokens from L1 > L2 with the classic bridge. The tokens where added to my account in less than 5 minutes. But the pending message is still showing on the gateway. I think it has to do with the fact that in my history tab, there is a duplicate of the transaction. It is shown twice. I think someone in telegram had the same issue.

![Pending Classic Bridge](https://user-images.githubusercontent.com/90399189/152643556-49193dd7-b7b7-4575-ada7-a7b88e777f92.png)

**Comment by JettaRed** [comment]
What does the Boba Explorer show?  Is your deposit to L2 showing in MetaMask?  Do you have your coins on a hardware wallet, i.e. Ledger or Trezor?

**Comment by MitchellUnknown** [comment]
> What does the Boba Explorer show? Is your deposit to L2 showing in MetaMask? Do you have your coins on a hardware wallet, i.e. Ledger or Trezor?

I have a Ledger connected with Metamask on Chrome. The boba explorer  is showing a succesful transaction from my boba tokens on L1 to L2. I remember when the tokens where available on the Boba Network, I immediately staked the tokens in the 5% staking tab. At that point the pending transaction screen was still showing. Metamask also showed the succesful transaction. Like I said everything is working, fine. Only the pending transaction message is still showing. I deleted metamask and reconnected my wallet and the pending message still shows. I switch to firefox and brave, it will show the pending message. I think the issue lays somewhere at the gateway code.

**Comment by JettaRed** [comment]
Sounds like you're OK, but I understand the concern over an "unresolved" issue.  It could very well be something whacky with the Ledger.  I know it was messing up the L2 to L1 bridge last week.  Not sure if that has been fixed or not.

**Comment by MitchellUnknown** [comment]
I will check if it’s still a problem, the next time I bridge some funds over. Thanks!

**Comment by JettaRed** [comment]
You may also consider getting a Trezor and setting it up with your 24 word seed phrase from your Ledger. That way you will have two devices holding your coins should one start acting whanky. It is always a good idea to have a backup or work-around in place. Remember, your wallet is those 12 or 24 words.

**Comment by CAPtheorem** [comment]
Looks like this is all resolved. If not, please reopen.

**Comment by MitchellUnknown** [comment]
Yes, its resolved! Great work 🚀
