### ISSUE TITLE
Boba bridge Rinkeby RPC

### ISSUE THREAD

**Issue by sirkaopad1** [omgnetwork/optimism-v2#368]
I was bridging to test a Boba game on Rinkery testnet.  https://prnt.sc/26qiicb  
when I switch network on on the Boba testnet gateway it gets stuck adding 'OMGx RPC'  https://prnt.sc/26qiivn

**Comment by CAPtheorem** [comment]
This is related to an old configuration entry in your local MetaMask. Please remove any outdated chains such as OMGx, which would point to the wrong RPC endpoints. If you ever have a problem like that, just remove the entry, and the gateway should add the correct settings on its own.
