### ISSUE TITLE
Turing returns incorrect error code

### ISSUE THREAD

**Issue by mmontour1306** [omgnetwork/optimism-v2#404]
When a Turing contract reverts after receiving its off-chain response, the user sees:

Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":142,\"error\":{\"code\":-32000,\"message\":\"turing retry needed\"}}\n", error={"code":-32000},

This is an internal error code which triggers an "eth_estimateGas" in a blocking-safe context. It should not be user-visible. Instead the actual revert string from the contract should be passed through.

**Comment by CAPtheorem** [comment]
Disabling the Turing cache for now
