### ISSUE TITLE
Approveal fails

### ISSUE THREAD

**Issue by yflor** [omgnetwork/optimism-v2#413]
Hi, when I'm trying to put more usdt to the liq.pool L2, i get the following message: sending a transaction requires a signer (operation="sendTransaction", code=UNSUPPORTED_OPERATION, version=contracts/5.4.1)

**Comment by alongline** [comment]
I am also receiving this same error, when I try to use the earn page depositing anything. I was able to stake the boba but nothing else.  I have already updated all browsers and metamask and turned signing on etc. Any clue?

**Comment by CAPtheorem** [comment]
Thanks for the report - reproducing now.

**Comment by CAPtheorem** [comment]
Bug confirmed - fixing

**Comment by CAPtheorem** [comment]
Please try now - should be fixed

**Comment by alongline** [comment]
Works as great as before for me.  Thank you.

**Comment by yflor** [comment]
Thanks. Works fine now.
