### ISSUE TITLE
STEP 0, NO SR HASH YET, PENDING

### ISSUE THREAD

**Issue by Nr-5** [omgnetwork/optimism-v2#427]
Good day,

After claiming the airdrop I wanted to transfer my OMG back to Layer 1 but I got this message:

STEP 0, NO SR HASH YET, PENDING

The tx hash is: 0x5757f0253977efe9a01ddb3bc89f298460c16808626677cdad46a44ebddfc1e8

My OMG is now not in L2 or in L1. Any help would be appreciated.

**Comment by CAPtheorem** [comment]
Hello @Nr-5 - looks like this TX cleared 13 hrs 17 mins ago, judging from Etherscan. Let me know If you have any other questions.
